apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ingress-ip-pool
  nodeSelectors:
    - matchLabels:
        node-role.kubernetes.io/router: ""