apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "_helpers-minio.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "_helpers-minio.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "_helpers-minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "_helpers-minio.name" . }}
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
          envFrom:
            - secretRef:
                name: {{ include "_helpers-minio.name" . }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: storage
              mountPath: "/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "_helpers-minio.name" . }}