apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "_helpers-minio.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "_helpers-minio.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual