apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
    - port: 43087
      targetPort: 43087
  selector:
    app: minio